application: appmusichub

version: 1

runtime: python

api_version: 1



handlers:

- url: /js

  static_dir: js



- url: /img

  static_dir: images

  

- url: /css

  static_dir: css

- url: /fonts

  static_dir: fonts

- url: /less

  static_dir: less


- url: /.*

  static_files: index.html

  upload: index.html


